# Generated by Django 4.0 on 2021-12-24 11:31

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsmodel',
            name='credential',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
